services:
  cognito:
    container_name: cognito_container
    build:
      context: .
      dockerfile: tmp.cognito.dockerfile
      args:
        VERSION: "5.0.25"
    ports:
      - 3001:3000
    restart: on-failure
    networks:
      - internal
  api:
    container_name: api_container
    build:
      context: ../app/api
      dockerfile: tmp.node.dockerfile
      target: development
      args:
        NODE_VERSION: "22-alpine"
    tty: true
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - ../app/api:/usr/app
  frontend:
    container_name: ui_container
    build:
      context: ../app/web-ui
      dockerfile: tmp.node.dockerfile
      target: development
      args:
        NODE_VERSION: "22-alpine"
    tty: true
    networks:
      - internal
    ports:
      - 4200:4200
    volumes:
      - ../app/web-ui:/usr/app
  terraform:
    container_name: terraform_container
    build:
      context: .
      dockerfile: tmp.terraform.dockerfile
      target: development
      args:
        TERRAFORM_VERSION: "1.10.3"
        AWS_CLI_VERSION: "2.22.27"
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-northeast-1
    volumes:
      - ../terraform:/usr/terraform
    networks:
      - internal

networks:
  internal: {}
